"""Add IP address to Question

Revision ID: aca2875d8b68
Revises: 6108c2401d8a
Create Date: 2025-01-15 13:04:19.100040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca2875d8b68'
down_revision = '6108c2401d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_question")
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=False, server_default='0.0.0.0'))
        batch_op.alter_column('question_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('question') as batch_op:
        batch_op.alter_column('ip_address', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_text',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
